spring:
  datasource:
    url:
      read-only: jdbc:mysql://localhost:3306/test
      read-write: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  data:
    mongodb:
      username: test
      password: test1234
      port: 27017
      host: localhost
      authentication-database: admin
      database: test

  jpa:
    show-sql: true